AspTarefas/Models/ErrorViewModel.cs
using System;

namespace AspTarefas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspTarefas/Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspTarefas.Models
{
    public class Tarefa
    {
        public int TarefaId { get; set; }

        public string Nome { get; set; }

        public string Descricao { get; set; }


        [DataType(DataType.DateTime)]
        public DateTime Inicio { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime Fim { get; set; }

        public string Importancia { get; set; }

        // testar depois [DataType(DataType.Upload)]
        public byte[] Foto {get; set;}
    }
}

AspTarefas/Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspTarefas.Data;
using AspTarefas.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace AspTarefas.Controllers
{
    public class TarefaController : Controller
    {
        private readonly TarefaContext _context;

        public TarefaController(TarefaContext context)
        {
            _context = context;
        }

        // GET: Tarefa
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tarefas.ToListAsync());
        }

        // GET: Tarefa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas
                .FirstOrDefaultAsync(m => m.TarefaId == id);
            if (tarefa == null)
            {
                return NotFound();
            }

            return View(tarefa);
        }

        // GET: Tarefa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tarefa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TarefaId,Nome,Descricao,Inicio,Fim,Importancia,Foto")] Tarefa tarefa, IFormFile foto)
        {
            if (ModelState.IsValid)
            {
                if (foto != null)
                {
                    byte[] b;
                    using (var or = foto.OpenReadStream())
                    {
                        using (var ms = new MemoryStream())
                        {
                            or.CopyTo(ms);
                            b = ms.ToArray();
                        }
                    }
                    tarefa.Foto = b;
                }

                _context.Add(tarefa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }

        public IActionResult pegarFoto(int id)
        {
            byte[] b = _context.Tarefas.Find(id).Foto;

            return File(b, "image/jpg");
        }

        // GET: Tarefa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas.FindAsync(id);
            if (tarefa == null)
            {
                return NotFound();
            }
            return View(tarefa);
        }

        // POST: Tarefa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TarefaId,Nome,Descricao,Inicio,Fim,Importancia")] Tarefa tarefa)
        {
            if (id != tarefa.TarefaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarefa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarefaExists(tarefa.TarefaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }

        // GET: Tarefa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas
                .FirstOrDefaultAsync(m => m.TarefaId == id);
            if (tarefa == null)
            {
                return NotFound();
            }

            return View(tarefa);
        }

        // POST: Tarefa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tarefa = await _context.Tarefas.FindAsync(id);
            _context.Tarefas.Remove(tarefa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TarefaExists(int id)
        {
            return _context.Tarefas.Any(e => e.TarefaId == id);
        }
    }
}

AspTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspTarefas</title>

    <environment include="Development">
        <link href="~/bundle.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/bundle.min.css" rel="stylesheet" />
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Tarefa" asp-action="Index">AspTarefas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item"> <!-- link adicinado por mim -->
                            <a class="nav-link text-dark" href="https://github.com/johnatanlima" rel="external" target="_blank"> Repo GITHUB </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AspTarefas - <a asp-area="" asp-controller="Tarefa" asp-action="Index">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <scrip src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </scrip>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AspTarefas/Views/Tarefa/Create.cshtml
@model AspTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tarefa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inicio" class="control-label"></label>
                <input asp-for="Inicio" class="form-control" type="datetime-local"/>
                <span asp-validation-for="Inicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fim" class="control-label"></label>
                <input asp-for="Fim" class="form-control" type="datetime-local" />
                <span asp-validation-for="Fim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importancia" class="control-label"></label>
                <input asp-for="Importancia" class="form-control" />
                <span asp-validation-for="Importancia" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" type="file" name="foto" id="foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspTarefas/Views/Tarefa/Delete.cshtml
@model AspTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tarefa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importancia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importancia)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TarefaId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspTarefas/Views/Tarefa/Details.cshtml
@model AspTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tarefa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importancia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importancia)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Action("pegarFoto", "Tarefa", new {id = Model.TarefaId} )" />
        </dt>
         @Html.DisplayFor(model => model.Foto)
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TarefaId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AspTarefas/Views/Tarefa/Edit.cshtml
@model AspTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tarefa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TarefaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inicio" class="control-label"></label>
                <input asp-for="Inicio" class="form-control" type="datetime-local"/>
                <span asp-validation-for="Inicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fim" class="control-label"></label>
                <input asp-for="Fim" class="form-control" type="datetime-local"/>
                <span asp-validation-for="Fim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importancia" class="control-label"></label>
                <input asp-for="Importancia" class="form-control" />
                <span asp-validation-for="Importancia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspTarefas/Views/Tarefa/Index.cshtml
@model IEnumerable<AspTarefas.Models.Tarefa>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importancia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Foto).ToString()
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fim)
            </td>

                @if (item.Importancia == "Baixa")
                 {
                    <td class="text-info">@Html.DisplayFor(modelItem => item.Importancia)</td>
                 }
                 
                @if (item.Importancia == "Média")
                 {
                    <td class="text-warning">@Html.DisplayFor(modelItem => item.Importancia)</td>
                 }
                 @if (item.Importancia == "Critica")
                 {
                    <td class="text-danger">@Html.DisplayFor(modelItem => item.Importancia)</td>
                 }

            <td>
                <img src="@Url.Action("pegarFoto", "Tarefa", new {id = item.TarefaId} )" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TarefaId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TarefaId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TarefaId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>